languageCode = "en-us"
title = "Wodevup"
baseurl = "http://wodevup.com/"
theme = "aerial"

[params]
  name = "Wodevup"
  about = "Grupo de mulheres de tecnologia"
  copyright = "Untitled"
  #Disable the scrolling background by entering any string for bg_scroll. Enable by leaving bg_scroll empty.
  bg_scroll = ""
  favicon = "/static/images/favicon.png"

[[params.social]]
  medium = "Twitter"
  icon = "twitter"
  link = "https://twitter.com/wodevup_rj"

[[params.social]]
  medium = "Facebook"
  icon = "facebook"
  link = "https://www.facebook.com/wodevup"

[[params.social]]
  medium = "Instagram"
  icon = "instagram"
  link = "https://www.instagram.com/wodevup/"

  [[params.social]]
    medium = "Telegram"
    icon = "telegram"
    link = "https://t.me/joinchat/JRPLvlgBQzayNnm6i6jPRA"

[[params.social]]
  medium = "Github"
  icon = "github"
  link = "https://github.com/wodevup"
